### ISSUE TITLE
File google-services.json is missing. The Google Services Plugin cannot function without it. 

### ISSUE THREAD

**Issue by refaatcrafts** [philipplackner/SpotifyCloneYT#7]
When I make clone for this project and run it ,It give me error massage tell me the following

Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Users\Hassan\AndroidStudioProjects\SpotifyCloneYT\app\src\nullnull\google-services.json
  C:\Users\Hassan\AndroidStudioProjects\SpotifyCloneYT\app\src\debug\google-services.json
  C:\Users\Hassan\AndroidStudioProjects\SpotifyCloneYT\app\src\nullnullDebug\google-services.json

**Comment by refaatcrafts** [comment]
I Solved it is a problem in firebase connection

**Comment by VCE-K** [comment]
Hello, international friends, I also encountered this problem, I would like to ask, how to solve this problem?
你好，国际朋友，我也遇到了这个问题，我想请教一下，怎样解决这个问题？
